### ISSUE TITLE
Error: dns service error: unknown at Error(native) [as part of AirSonos]

### ISSUE THREAD

**Issue by tslgit** [stephen/nodetunes#35]
I am getting "Error: dns service error: unknown"

I am trying to run Airsonos on Freenas in a jail. Avahi is also running in the jail.
My Sonos system can be found, but registering it fails.

Any idea how to solve this?

The log of AirSonos:
root@airsonos:/ # airsonos --verbose                                                                   *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Searching for Sonos devices on network...
Setting up AirSonos for Kitchen {192.168.xxx.xxx:1400}
  nodetunes:server starting nodetunes server (Kitchen (AirSonos)) +0ms
/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^
Error: dns service error: unknown
    at Error (native)
    at new Advertisement (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/lib/advertisement.js:64:10)
    at NodeTunes.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/server.js:74:21)
    at Server.g (events.js:199:16)
    at Server.emit (events.js:104:17)
    at net.js:1171:12
    at process._tickCallback (node.js:355:11)

**Comment by tslgit** [comment]
dbus was disabled in the avahi-daemon conf file. Enabling it, solved this issue
