### ISSUE TITLE
Error: Invalid Key Length

### ISSUE THREAD

**Issue by ghost** [stephen/nodetunes#46]
Ummm... just started running it (please note i HAVE done the fix included in #302 and it does not work for me on a macOS Sierra) My output code:
Error: Invalid key length
at error (native)
at new Decipheriv (crypto.js:239:16) (not sure about this! everywhere else it says 238:15, not for me)
at Object.decryptAudioData (/Users/YoungFamily/airsonos/node_modules/nodetunes/lib/helper.js:141:25)
at RtpServer.<anonymous> (/Users/YoungFamily/airsonos/node_modules/nodetunes/lib/rtp.js:32:23)
at emitTwo (events.js:106:13
at Socket.emit (events.js:191:7)
at UDP.onMessage (dgram.js:550:8)

Comments:
Please note that i typed this all up so if you see something wrong that i did not state like the 239:16, then please dont tell me im not the best at typing.
Thanks! I hope to hear back soon.

**Comment by bbram** [comment]
Same here. Keep getting the Error: Invalid key length


`Error: Invalid key length
    at Error (native)
    at new Decipheriv (crypto.js:239:16)
    at Object.Decipheriv (crypto.js:236:12)
    at Object.decryptAudioData (/usr/lib/node_modules/airsonos/node_modules/nodetunes/lib/helper.js:141:25)
    at RtpServer.<anonymous> (/usr/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtp.js:32:23)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:550:8)
`

**Comment by gpjt** [comment]
Same here.

**Comment by gpjt** [comment]
Ah, OK.  It's caused by a Node version update.  @Kolky has written a [pull request](https://github.com/stephen/nodetunes/pull/42) for it, but it hasn't been accepted into the main nodetunes repository.

You can install it yourself by uninstalling the existing version (for example, `npm uninstall nodetunes`) and then installing the patched version with `npm install git://github.com/Kolky/nodetunes.git#master`
