### ISSUE TITLE
airsonos Disconnecting

### ISSUE THREAD

**Issue by tylergarnett** [stephen/nodetunes#47]
I followed all of the install instructions for airsonos. Everything seemed to be installed correctly and it showed up in my systems preferences/sound. However, when I click on the speaker and then try to play something with sound, the airsonos disappears. I have to type airsonos in the terminal to get it back. Then the same problem happens when I click on it and play a quicktime or something online that has sound. It just disappears. Can someone help me?

**Comment by tylergarnett** [comment]
It stays:

Error: Invalid key length
    at Error (native)
    at new Decipheriv (crypto.js:239:16)
    at Object.Decipheriv (crypto.js:236:12)
    at Object.decryptAudioData (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/helper.js:141:25)
    at RtpServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtp.js:32:23)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:550:8)

**Comment by tylergarnett** [comment]
Nevermind. I figured it out by reading other issues you fixed. Now I just have to deal with the lag in playback.
